### ISSUE TITLE
Select LoRA dropdown - list issues

### ISSUE THREAD

**Issue by dzeitman** [CharafChnioune/MFLUX-WEBUI#8]
Select LoRA dropdown includes the Mac OS .link files --  It would be great to filter these out so the list shows only the actual LoRA files.  
<img width="643" alt="Lora_list" src="https://github.com/user-attachments/assets/cbae7797-47bf-46e7-a5c3-a0418256b4e1">

**Comment by CharafChnioune** [comment]
This has been fixed in the development branch! The LoRA dropdown will now:

1. Only show actual `.safetensors` files
2. Filter out `.link` files and symlinks
3. Clean up any duplicate extensions
4. Sort the list alphabetically (case-insensitive)

This should make the LoRA selection much cleaner and easier to use. The changes are already available in the development branch - let me know if you see any other file types that should be filtered out. Try it out let me know if you run into some bugs
